#!/bin/sh
# Generated by aftwin. DO NOT EDIT.
set -eu

configure_vrf() {
    vrf="$1"
    table="$2"
    interface="$3"
    address="$4"
    gateway="$5"

    ip link show "$vrf" >/dev/null 2>&1 || ip link add "$vrf" type vrf table "$table"
    ip link set dev "$vrf" up
    ip link set dev "$interface" down
    ip addr flush dev "$interface"
    ip link set dev "$interface" master "$vrf"
    ip addr replace "$address" dev "$interface"
    ip link set dev "$interface" up
    ip route replace vrf "$vrf" default via "$gateway" dev "$interface"
}

configure_vrf fabric-a 1001 eth1 10.0.1.3/31 10.0.1.2
configure_vrf fabric-b 1002 eth2 10.1.1.3/31 10.1.1.2
