"""Deterministic Containerlab topology rendering."""

from collections.abc import Mapping
from typing import Any

import yaml

from aftwin.backend.contract import PlatformBackend
from aftwin.domain.enums import NodeRole
from aftwin.domain.models import Fabric

GENERATED_HEADER = "# Generated by aftwin. DO NOT EDIT.\n"
NODE_GROUPS = {
    NodeRole.SPINE: "spine",
    NodeRole.LEAF: "leaf",
    NodeRole.COMPUTE: "server",
    NodeRole.STORAGE: "server",
}


def render_containerlab_topology(
    fabric: Fabric,
    platform_nodes: Mapping[str, Mapping[str, str]],
    backends: Mapping[str, PlatformBackend],
) -> str:
    """Render a stable Containerlab topology for a validated fabric."""
    nodes: dict[str, dict[str, Any]] = {}
    node_backends: dict[str, PlatformBackend] = {}
    for node in sorted(fabric.nodes, key=lambda item: item.name):
        platform = platform_nodes[node.platform]
        backend = backends[node.platform]
        node_backends[node.name] = backend
        nodes[node.name] = backend.containerlab_node(
            node,
            kind=platform["kind"],
            image=platform["image"],
            group=NODE_GROUPS[node.role],
            node_type=platform.get("type"),
        )

    endpoint_pairs = [
        tuple(
            sorted(
                f"{endpoint.node}:"
                f"{node_backends[endpoint.node].runtime_interface_name(endpoint.interface)}"
                for endpoint in (link.endpoint_a, link.endpoint_b)
            )
        )
        for link in fabric.links
    ]
    links = [{"endpoints": list(pair)} for pair in sorted(endpoint_pairs)]
    payload = {
        "name": fabric.name,
        "mgmt": {
            "network": "aftwin-mgmt",
            "ipv4-subnet": "172.30.30.0/24",
            "ipv6-subnet": "3fff:172:30:30::/64",
        },
        "topology": {"nodes": nodes, "links": links},
    }
    return GENERATED_HEADER + yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
