"""Deterministic Containerlab topology rendering."""

from collections.abc import Mapping
from typing import Any

import yaml

from aftwin.domain.enums import NodeRole
from aftwin.domain.models import Fabric

GENERATED_HEADER = "# Generated by aftwin. DO NOT EDIT.\n"


def render_containerlab_topology(
    fabric: Fabric, platform_nodes: Mapping[str, Mapping[str, str]]
) -> str:
    """Render a stable Containerlab topology for a validated fabric."""
    nodes: dict[str, dict[str, Any]] = {}
    for node in sorted(fabric.nodes, key=lambda item: item.name):
        platform = platform_nodes[node.platform]
        definition: dict[str, Any] = {
            "kind": platform["kind"],
            "image": platform["image"],
        }
        if node.role is NodeRole.COMPUTE:
            definition["binds"] = [
                f"configs/endpoints/{node.name}/setup.sh:/usr/local/sbin/aftwin-endpoint-setup:ro"
            ]
            definition["exec"] = ["/bin/sh /usr/local/sbin/aftwin-endpoint-setup"]
            definition["sysctls"] = {
                "net.ipv4.ip_forward": 0,
                "net.ipv4.conf.all.rp_filter": 0,
                "net.ipv4.conf.default.rp_filter": 0,
            }
        else:
            definition["binds"] = [
                f"configs/routers/{node.name}/daemons:/etc/frr/daemons:ro",
                f"configs/routers/{node.name}/frr.conf:/etc/frr/frr.conf:ro",
            ]
            definition["sysctls"] = {
                "net.ipv4.ip_forward": 1,
                "net.ipv4.conf.all.rp_filter": 0,
                "net.ipv4.conf.default.rp_filter": 0,
            }
        nodes[node.name] = definition

    endpoint_pairs = [
        tuple(
            sorted(
                (
                    f"{link.endpoint_a.node}:{link.endpoint_a.interface}",
                    f"{link.endpoint_b.node}:{link.endpoint_b.interface}",
                )
            )
        )
        for link in fabric.links
    ]
    links = [{"endpoints": list(pair)} for pair in sorted(endpoint_pairs)]
    payload = {"name": fabric.name, "topology": {"nodes": nodes, "links": links}}
    return GENERATED_HEADER + yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
