"""Deterministic Linux endpoint VRF setup rendering."""

from aftwin.compiler.expected_state import EndpointPrefix
from aftwin.domain.models import Node


def render_endpoint_setup(node: Node, prefixes: tuple[EndpointPrefix, ...]) -> str:
    """Render idempotent per-plane VRF configuration for one endpoint."""
    node_prefixes = tuple(
        sorted(
            (item for item in prefixes if item.node == node.name), key=lambda item: item.plane.value
        )
    )
    if not node_prefixes:
        raise ValueError(f"endpoint has no fabric attachments: {node.name}")
    lines = [
        "#!/bin/sh",
        "# Generated by aftwin. DO NOT EDIT.",
        "set -eu",
        "",
        "configure_vrf() {",
        '    vrf="$1"',
        '    table="$2"',
        '    interface="$3"',
        '    address="$4"',
        '    gateway="$5"',
        "",
        '    ip link show "$vrf" >/dev/null 2>&1 || ip link add "$vrf" type vrf table "$table"',
        '    ip link set dev "$vrf" up',
        '    ip link set dev "$interface" down',
        '    ip addr flush dev "$interface"',
        '    ip link set dev "$interface" master "$vrf"',
        '    ip addr replace "$address" dev "$interface"',
        '    ip link set dev "$interface" up',
        '    ip route replace vrf "$vrf" default via "$gateway" dev "$interface"',
        "}",
        "",
    ]
    for prefix in node_prefixes:
        table = 1001 if prefix.plane.value == "a" else 1002
        lines.append(
            f"configure_vrf {prefix.vrf} {table} {prefix.interface} "
            f"{prefix.address}/{prefix.prefix.prefixlen} {prefix.gateway}"
        )
    return "\n".join(lines) + "\n"
