"""Deterministic FRR configuration rendering."""

from aftwin.domain.enums import LinkKind, NodeRole
from aftwin.domain.models import Fabric, Interface, LinkEndpoint, Node

DAEMONS = "# Generated by aftwin. DO NOT EDIT.\nbgpd=yes\nfrr_profile=datacenter\n"


def _interface_index(fabric: Fabric) -> dict[tuple[str, str], Interface]:
    return {
        (node.name, interface.name): interface
        for node in fabric.nodes
        for interface in node.interfaces
    }


def _other_endpoint(node: Node, endpoint_a: LinkEndpoint, endpoint_b: LinkEndpoint) -> LinkEndpoint:
    return endpoint_b if endpoint_a.node == node.name else endpoint_a


def render_frr_config(fabric: Fabric, node: Node) -> str:
    """Render one router's interfaces and eBGP intent."""
    if node.role not in {NodeRole.SPINE, NodeRole.LEAF} or node.asn is None:
        raise ValueError(f"FRR renderer requires a router with an ASN: {node.name}")
    if node.loopback is None:
        raise ValueError(f"FRR renderer requires a loopback: {node.name}")

    interfaces = _interface_index(fabric)
    node_index = {item.name: item for item in fabric.nodes}
    lines = [
        "! Generated by aftwin. DO NOT EDIT.",
        "frr version 10.3.4",
        "frr defaults datacenter",
        f"hostname {node.name}",
        "service integrated-vtysh-config",
        "!",
        "ip forwarding",
        "!",
    ]
    for interface in sorted(node.interfaces, key=lambda item: item.name):
        if not interface.addresses:
            continue
        lines.extend([f"interface {interface.name}"])
        for address in sorted(
            interface.addresses, key=lambda item: (int(item.ip), item.network.prefixlen)
        ):
            lines.append(f" ip address {address}")
        lines.extend(["exit", "!"])

    neighbors: list[tuple[str, int]] = []
    for link in fabric.links:
        if link.kind is not LinkKind.FABRIC:
            continue
        endpoints = (link.endpoint_a, link.endpoint_b)
        if node.name not in {endpoints[0].node, endpoints[1].node}:
            continue
        peer_endpoint = _other_endpoint(node, *endpoints)
        peer = node_index[peer_endpoint.node]
        peer_interface = interfaces[(peer_endpoint.node, peer_endpoint.interface)]
        if peer.asn is None or len(peer_interface.addresses) != 1:
            raise ValueError(f"invalid BGP peer intent: {peer.name}")
        neighbors.append((str(peer_interface.addresses[0].ip), peer.asn))

    lines.extend(
        [
            f"router bgp {node.asn}",
            f" bgp router-id {node.loopback.ip}",
            " no bgp ebgp-requires-policy",
            " bgp bestpath as-path multipath-relax",
        ]
    )
    for address, asn in sorted(
        neighbors, key=lambda item: tuple(int(part) for part in item[0].split("."))
    ):
        lines.append(f" neighbor {address} remote-as {asn}")
    lines.extend([" !", " address-family ipv4 unicast", f"  network {node.loopback}"])
    if node.role is NodeRole.LEAF:
        for interface in sorted(node.interfaces, key=lambda item: item.name):
            if interface.role.value == "host":
                for address in interface.addresses:
                    lines.append(f"  network {address.network}")
    for address, _ in sorted(
        neighbors, key=lambda item: tuple(int(part) for part in item[0].split("."))
    ):
        lines.append(f"  neighbor {address} activate")
    lines.extend(["  maximum-paths 64", " exit-address-family", "exit", "!", "end"])
    return "\n".join(lines) + "\n"
