"""Deterministic Nokia SR Linux CLI configuration rendering."""

from ipaddress import IPv4Network

from aftwin.domain.enums import InterfaceRole, LinkKind, NodeRole
from aftwin.domain.models import Fabric, Interface, LinkEndpoint, Node

GENERATED_HEADER = "# Generated by aftwin. DO NOT EDIT."
PREFIX_SET = "aftwin-fabric-prefixes"
EXPORT_POLICY = "aftwin-fabric-export"
PEER_GROUP = "aftwin-fabric"


def srlinux_interface_name(source_name: str) -> str:
    """Map one source interface name to its SR Linux configuration name."""
    if source_name == "lo":
        return "system0"
    if source_name.startswith("eth") and source_name[3:].isdigit():
        return f"ethernet-1/{source_name[3:]}"
    raise ValueError(f"interface name has no SR Linux mapping: {source_name}")


def srlinux_containerlab_interface_name(source_name: str) -> str:
    """Map one source interface name to Containerlab's SR Linux endpoint name."""
    if source_name.startswith("eth") and source_name[3:].isdigit():
        return f"e1-{source_name[3:]}"
    raise ValueError(f"interface name has no SR Linux Containerlab mapping: {source_name}")


def _interface_index(fabric: Fabric) -> dict[tuple[str, str], Interface]:
    return {
        (node.name, interface.name): interface
        for node in fabric.nodes
        for interface in node.interfaces
    }


def _other_endpoint(node: Node, endpoint_a: LinkEndpoint, endpoint_b: LinkEndpoint) -> LinkEndpoint:
    return endpoint_b if endpoint_a.node == node.name else endpoint_a


def _exported_prefixes(node: Node, loopback: IPv4Network) -> tuple[IPv4Network, ...]:
    """Loopback and attached host prefixes, mirroring the FRR network statements."""
    prefixes = {loopback}
    if node.role is NodeRole.LEAF:
        for interface in node.interfaces:
            if interface.role is InterfaceRole.HOST:
                prefixes.update(address.network for address in interface.addresses)
    return tuple(sorted(prefixes, key=lambda item: (int(item.network_address), item.prefixlen)))


def render_srlinux_config(fabric: Fabric, node: Node) -> str:
    """Render one router's interfaces and eBGP intent as CLI set commands."""
    if node.role not in {NodeRole.SPINE, NodeRole.LEAF} or node.asn is None:
        raise ValueError(f"SR Linux renderer requires a router with an ASN: {node.name}")
    if node.loopback is None:
        raise ValueError(f"SR Linux renderer requires a loopback: {node.name}")

    interfaces = _interface_index(fabric)
    node_index = {item.name: item for item in fabric.nodes}
    lines = [GENERATED_HEADER]

    attached: list[str] = []
    for interface in sorted(node.interfaces, key=lambda item: item.name):
        if not interface.addresses:
            continue
        name = srlinux_interface_name(interface.name)
        lines.extend(
            [
                f"set / interface {name} admin-state enable",
                f"set / interface {name} subinterface 0 admin-state enable",
                f"set / interface {name} subinterface 0 ipv4 admin-state enable",
            ]
        )
        for address in sorted(
            interface.addresses, key=lambda item: (int(item.ip), item.network.prefixlen)
        ):
            lines.append(f"set / interface {name} subinterface 0 ipv4 address {address}")
        attached.append(f"{name}.0")

    lines.append("set / network-instance default type default")
    lines.append("set / network-instance default admin-state enable")
    lines.extend(f"set / network-instance default interface {name}" for name in sorted(attached))

    for prefix in _exported_prefixes(node, node.loopback.network):
        lines.append(
            f"set / routing-policy prefix-set {PREFIX_SET} prefix {prefix} mask-length-range exact"
        )
    lines.extend(
        [
            f"set / routing-policy policy {EXPORT_POLICY} default-action policy-result reject",
            f"set / routing-policy policy {EXPORT_POLICY} statement 10 "
            f"match prefix-set {PREFIX_SET}",
            f"set / routing-policy policy {EXPORT_POLICY} statement 10 action policy-result accept",
            f"set / routing-policy policy {EXPORT_POLICY} statement 20 match protocol bgp",
            f"set / routing-policy policy {EXPORT_POLICY} statement 20 action policy-result accept",
        ]
    )

    bgp = "set / network-instance default protocols bgp"
    lines.extend(
        [
            f"{bgp} admin-state enable",
            f"{bgp} autonomous-system {node.asn}",
            f"{bgp} router-id {node.loopback.ip}",
            f"{bgp} ebgp-default-policy import-reject-all false",
            f"{bgp} ebgp-default-policy export-reject-all false",
            f"{bgp} afi-safi ipv4-unicast admin-state enable",
            f"{bgp} afi-safi ipv4-unicast multipath allow-multiple-as true",
            f"{bgp} afi-safi ipv4-unicast multipath maximum-paths 64",
            f"{bgp} group {PEER_GROUP} admin-state enable",
            f"{bgp} group {PEER_GROUP} export-policy [ {EXPORT_POLICY} ]",
            f"{bgp} group {PEER_GROUP} afi-safi ipv4-unicast admin-state enable",
        ]
    )

    neighbors: list[tuple[str, int]] = []
    for link in fabric.links:
        if link.kind is not LinkKind.FABRIC:
            continue
        endpoints = (link.endpoint_a, link.endpoint_b)
        if node.name not in {endpoints[0].node, endpoints[1].node}:
            continue
        peer_endpoint = _other_endpoint(node, *endpoints)
        peer = node_index[peer_endpoint.node]
        peer_interface = interfaces[(peer_endpoint.node, peer_endpoint.interface)]
        if peer.asn is None or len(peer_interface.addresses) != 1:
            raise ValueError(f"invalid BGP peer intent: {peer.name}")
        neighbors.append((str(peer_interface.addresses[0].ip), peer.asn))

    for address, asn in sorted(
        neighbors, key=lambda item: tuple(int(part) for part in item[0].split("."))
    ):
        lines.append(f"{bgp} neighbor {address} admin-state enable")
        lines.append(f"{bgp} neighbor {address} peer-group {PEER_GROUP}")
        lines.append(f"{bgp} neighbor {address} peer-as {asn}")
    return "\n".join(lines) + "\n"
