import json
import shutil
import subprocess
from ipaddress import IPv4Address
from pathlib import Path
from typing import Any

import pytest
import yaml

from aftwin.backend.registry import get_backend
from aftwin.backend.srlinux import SrLinuxObservedStateCollector
from aftwin.compiler.compiler import compile_fabric, load_platform_map
from aftwin.domain.enums import NETWORK_ROLES
from aftwin.netbox.fixture import fixture_to_fabric, load_fixture
from aftwin.policy.engine import PolicyEngine
from aftwin.policy.profile import load_policy_profile
from aftwin.render.srlinux import (
    render_srlinux_config,
    srlinux_containerlab_interface_name,
    srlinux_interface_name,
)

PROJECT_ROOT = Path(__file__).resolve().parents[2]
FRR_FIXTURE = PROJECT_ROOT / "fixtures/mini-dual-plane.yaml"
FRR_PROFILE = PROJECT_ROOT / "config/policies/mini-dual-plane.yaml"
FRR_PLATFORMS = PROJECT_ROOT / "config/platform-map.yaml"
SRL_FIXTURE = PROJECT_ROOT / "fixtures/mini-dual-plane-srlinux.yaml"
SRL_PROFILE = PROJECT_ROOT / "config/policies/mini-dual-plane-srlinux.yaml"
SRL_PLATFORMS = PROJECT_ROOT / "config/platform-map-srlinux.yaml"
SRL_GOLDEN = PROJECT_ROOT / "tests/golden/mini-dual-plane-srlinux"


def test_interface_names_map_to_srlinux_conventions() -> None:
    assert srlinux_interface_name("eth1") == "ethernet-1/1"
    assert srlinux_interface_name("eth12") == "ethernet-1/12"
    assert srlinux_interface_name("lo") == "system0"
    assert srlinux_containerlab_interface_name("eth3") == "e1-3"
    with pytest.raises(ValueError, match="no SR Linux mapping"):
        srlinux_interface_name("Ethernet1/1")
    with pytest.raises(ValueError, match="no SR Linux Containerlab mapping"):
        srlinux_containerlab_interface_name("lo")


def test_leaf_config_renders_bgp_policies_and_interfaces() -> None:
    fabric = fixture_to_fabric(load_fixture(SRL_FIXTURE))
    leaf = next(node for node in fabric.nodes if node.name == "leaf-a1")
    spine = next(node for node in fabric.nodes if node.name == "spine-a1")

    leaf_config = render_srlinux_config(fabric, leaf)
    spine_config = render_srlinux_config(fabric, spine)

    assert leaf_config.startswith("# Generated by aftwin. DO NOT EDIT.\n")
    assert "set / interface system0 subinterface 0 ipv4 address 10.255.0.101/32" in leaf_config
    assert "set / network-instance default interface ethernet-1/1.0" in leaf_config
    assert "set / network-instance default interface system0.0" in leaf_config
    assert "set / network-instance default protocols bgp autonomous-system 65101" in leaf_config
    assert "ebgp-default-policy import-reject-all false" in leaf_config
    assert "ebgp-default-policy export-reject-all false" in leaf_config
    assert "multipath max-paths-level-1 64" in leaf_config
    assert "neighbor 10.0.0.0 peer-as 65001" in leaf_config
    assert "neighbor 10.0.0.4 peer-as 65002" in leaf_config
    # Leaves export their loopback and attached host prefixes; spines export
    # only their loopback and re-advertise BGP routes.
    assert "prefix 10.0.1.0/31 mask-length-range exact" in leaf_config
    assert "prefix 10.255.0.101/32 mask-length-range exact" in leaf_config
    assert "prefix 10.0.1.0/31" not in spine_config
    assert "prefix 10.255.0.1/32 mask-length-range exact" in spine_config
    assert "statement 20 match protocol bgp" in spine_config
    # Fabric p2p /31 subnets must not be exported as originated prefixes.
    assert "prefix 10.0.0.0/31" not in leaf_config
    assert leaf_config.endswith("\n")


def test_endpoint_nodes_are_rejected_by_the_srlinux_renderer() -> None:
    fabric = fixture_to_fabric(load_fixture(SRL_FIXTURE))
    endpoint = next(node for node in fabric.nodes if node.name == "gpu01")

    with pytest.raises(ValueError, match="requires a router"):
        render_srlinux_config(fabric, endpoint)


def test_srlinux_containerlab_node_uses_native_kind_and_startup_config() -> None:
    fabric = fixture_to_fabric(load_fixture(SRL_FIXTURE))
    leaf = next(node for node in fabric.nodes if node.name == "leaf-a1")
    backend = get_backend("srlinux")

    definition = backend.containerlab_node(
        leaf,
        kind="nokia_srlinux",
        image="ghcr.io/nokia/srlinux:24.10.1",
        group="leaf",
        node_type="ixr-d2l",
    )

    assert definition == {
        "kind": "nokia_srlinux",
        "image": "ghcr.io/nokia/srlinux:24.10.1",
        "type": "ixr-d2l",
        "group": "leaf",
        "startup-config": "configs/routers/leaf-a1/srlinux.cli",
    }


def test_container_backends_reject_node_type_overrides() -> None:
    fabric = fixture_to_fabric(load_fixture(FRR_FIXTURE))
    leaf = next(node for node in fabric.nodes if node.name == "leaf-a1")

    with pytest.raises(ValueError, match="does not support a node type"):
        get_backend("frr").containerlab_node(
            leaf, kind="linux", image="quay.io/frrouting/frr:10.3.4", group="leaf", node_type="x"
        )


def _bgp_payload(*, namespaced: bool) -> dict[str, Any]:
    prefix = "srl_nokia-network-instance:" if namespaced else ""
    state = "srl_nokia-bgp:established" if namespaced else "established"
    return {
        f"{prefix}network-instance": [
            {
                "name": "default",
                "protocols": {
                    "bgp": {
                        "autonomous-system": 65101,
                        "router-id": "10.255.0.101",
                        "neighbor": [
                            {
                                "peer-address": "10.0.0.4",
                                "peer-as": 65002,
                                "session-state": "active",
                            },
                            {
                                "peer-address": "10.0.0.0",
                                "peer-as": 65001,
                                "session-state": state,
                            },
                        ],
                    }
                },
            }
        ]
    }


@pytest.mark.parametrize("namespaced", (False, True))
def test_parse_bgp_summary_normalizes_srlinux_state(namespaced: bool) -> None:
    collector = SrLinuxObservedStateCollector()

    observed = collector.parse_bgp_summary(
        "leaf-a1", json.dumps(_bgp_payload(namespaced=namespaced))
    )

    assert observed.router == "leaf-a1"
    assert observed.local_asn == 65101
    assert [neighbor.address for neighbor in observed.neighbors] == ["10.0.0.0", "10.0.0.4"]
    assert observed.neighbors[0].remote_asn == 65001
    assert observed.neighbors[0].state == "established"
    assert observed.neighbors[1].state == "active"


def test_parse_route_table_resolves_ecmp_groups_and_protocol_names() -> None:
    payload = {
        "network-instance": [
            {
                "name": "default",
                "route-table": {
                    "ipv4-unicast": {
                        "route": [
                            {
                                "ipv4-prefix": "10.0.1.0/31",
                                "route-type": "local",
                                "active": True,
                                "next-hop-group": 1,
                            },
                            {
                                "ipv4-prefix": "10.0.3.0/31",
                                "route-type": "bgp",
                                "active": True,
                                "next-hop-group": 2,
                            },
                            {
                                "ipv4-prefix": "192.0.2.0/24",
                                "route-type": "bgp",
                                "active": False,
                                "next-hop-group": 2,
                            },
                        ]
                    },
                    "next-hop-group": [
                        {"index": 1, "next-hop": [{"index": 0, "next-hop": 10}]},
                        {
                            "index": 2,
                            "next-hop": [
                                {"index": 0, "next-hop": 11},
                                {"index": 1, "next-hop": 12},
                            ],
                        },
                    ],
                    "next-hop": [
                        {"index": 10, "ip-address": "10.0.1.1"},
                        {"index": 11, "ip-address": "10.0.0.1"},
                        {"index": 12, "ip-address": "10.0.0.5"},
                    ],
                },
            }
        ]
    }
    collector = SrLinuxObservedStateCollector()

    observed = collector.parse_route_table("leaf-a1", json.dumps(payload))

    by_prefix = {str(route.prefix): route for route in observed.routes}
    assert set(by_prefix) == {"10.0.1.0/31", "10.0.3.0/31"}
    assert by_prefix["10.0.1.0/31"].protocol == "connected"
    assert by_prefix["10.0.1.0/31"].next_hops == (IPv4Address("10.0.1.1"),)
    assert by_prefix["10.0.3.0/31"].protocol == "bgp"
    assert by_prefix["10.0.3.0/31"].next_hops == (
        IPv4Address("10.0.0.1"),
        IPv4Address("10.0.0.5"),
    )


def test_same_normalized_fabric_compiles_for_frr_and_srlinux(tmp_path: Path) -> None:
    fabric = fixture_to_fabric(load_fixture(FRR_FIXTURE))
    swapped_nodes = tuple(
        node.model_copy(update={"platform": "srlinux"}) if node.role in NETWORK_ROLES else node
        for node in fabric.nodes
    )
    swapped = fabric.model_copy(update={"nodes": swapped_nodes})
    profile = load_policy_profile(FRR_PROFILE)

    frr_result = compile_fabric(fabric, load_platform_map(FRR_PLATFORMS), profile, tmp_path / "frr")
    srl_result = compile_fabric(
        swapped, load_platform_map(SRL_PLATFORMS), profile, tmp_path / "srl"
    )

    assert frr_result.node_count == srl_result.node_count
    assert frr_result.link_count == srl_result.link_count
    assert (tmp_path / "frr" / "expected-state.json").read_bytes() == (
        tmp_path / "srl" / "expected-state.json"
    ).read_bytes()

    frr_topology = yaml.safe_load((tmp_path / "frr" / "topology.clab.yml").read_text())
    srl_topology = yaml.safe_load((tmp_path / "srl" / "topology.clab.yml").read_text())
    assert srl_topology["topology"]["nodes"]["leaf-a1"]["kind"] == "nokia_srlinux"
    assert {"endpoints": ["gpu01:eth1", "leaf-a1:e1-3"]} in srl_topology["topology"]["links"]
    assert {"endpoints": ["gpu01:eth1", "leaf-a1:eth3"]} in frr_topology["topology"]["links"]


def _compile_srlinux_golden(output: Path) -> None:
    fabric = fixture_to_fabric(load_fixture(SRL_FIXTURE))
    profile = load_policy_profile(SRL_PROFILE)
    report = PolicyEngine().validate(fabric, profile)
    assert report.passed
    compile_fabric(fabric, load_platform_map(SRL_PLATFORMS), profile, output)


def _content_tree(root: Path) -> dict[str, bytes]:
    return {
        path.relative_to(root).as_posix(): path.read_bytes()
        for path in sorted(root.rglob("*"))
        if path.is_file()
    }


def test_srlinux_compiler_output_matches_committed_golden_tree(tmp_path: Path) -> None:
    _compile_srlinux_golden(tmp_path)

    assert _content_tree(tmp_path) == _content_tree(SRL_GOLDEN)


def test_srlinux_topology_is_accepted_by_containerlab_offline(tmp_path: Path) -> None:
    executable = shutil.which("containerlab")
    if executable is None:
        pytest.skip("containerlab is not installed")
    _compile_srlinux_golden(tmp_path)

    result = subprocess.run(
        [executable, "graph", "--offline", "--mermaid", "-t", str(tmp_path / "topology.clab.yml")],
        check=False,
        capture_output=True,
        text=True,
    )

    assert result.returncode == 0, result.stderr
    assert "deprecated" not in result.stderr.lower()


def test_srlinux_golden_nodes_are_native_nos_nodes(tmp_path: Path) -> None:
    _compile_srlinux_golden(tmp_path)
    topology = yaml.safe_load((tmp_path / "topology.clab.yml").read_text())
    inventory = json.loads((tmp_path / "inventory.json").read_text())

    assert topology["name"] == "mini-dual-plane-srlinux"
    routers = [
        name
        for name, definition in topology["topology"]["nodes"].items()
        if definition["kind"] == "nokia_srlinux"
    ]
    assert len(routers) == 8
    for name in routers:
        definition = topology["topology"]["nodes"][name]
        assert definition["image"] == "ghcr.io/nokia/srlinux:24.10.1"
        assert definition["type"] == "ixr-d2l"
        assert definition["startup-config"] == f"configs/routers/{name}/srlinux.cli"
    assert {
        "name": "leaf-a1",
        "role": "fabric-leaf",
        "platform": "srlinux",
        "renderer": "srlinux",
    } in inventory["nodes"]
